name: ROS Lint

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    container:
      image: althack/ros2:humble-dev
    strategy:
      fail-fast: false
      matrix:
        linter: [lint_cmake, xmllint, pep257, flake8]
    steps:
      - uses: actions/checkout@v4
      - name: Run ament_${{ matrix.linter }}
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          if [[ "${{ matrix.linter }}" == "flake8" ]]; then
            ament_flake8 --config .github/ament_flake8.ini src/
          else
            ament_${{ matrix.linter }} src/
          fi
